### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rufuscoder** [rmariuzzo/cloud9-emmet-ext#1]
I don't know if you have already made the plugin and just haven't commited it yet or jsut haven't made it yet. If you haven't made it yet I would like to work on it. I would also like to use this in my new web IDE.

**Comment by rmariuzzo** [comment]
Hi @roffiscoder! I started to code a little, but nothing working _yet_. I started in the wrong the direction but I recently talked with the creator of ZenCoding (now is emmet.io) and he gave some advice. If you want to collaborate I will be more than happy. I will push my changes in a while so you can fork it.

**Comment by rmariuzzo** [comment]
Since its not an issue I'm closing it.

**Comment by rmariuzzo** [comment]
Hi @rufuscoder,

Just to let you and the rest of the world know that we have renamed this project to `c9-emmet-ext` instead of `c9-zencoding-ext`, that's because of a brand renaming of emmet (previously know as zen-coding).

Also, @rufuscoder, I want to inform you that I have put a list of _upcoming_ actions that need to be analyzed and probably implemented. That is if you still want to contribute on this project. This is the list: [https://github.com/rmariuzzo/cloud9-emmet-ext#available-actions](https://github.com/rmariuzzo/cloud9-emmet-ext#available-actions)

**Comment by rufuscoder** [comment]
Thanks for letting me know. I have some other projects going on right now but I will see what I can do later in the week.

**Comment by rmariuzzo** [comment]
Ok, when you feel like you have some time just let me know. Thanks.
